version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        hostname: dev-58283e8d
        restart: unless-stopped
        ports:
          - '5672:5672'
          - '15672:15672'
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq  

volumes:  
  rabbitmq_data:
    driver: local