version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        hostname: dev-58283e8d
        restart: unless-stopped
        ports:
          - '5672:5672'
          - '15672:15672'
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq  

    pixel-service:
        image: pixel-service:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: .
            dockerfile: ./src/Services/PixelService/Dockerfile
        environment:   
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - 5128:80
        depends_on:            
            - rabbitmq

    storage-service:
        image: storage-service:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: .
            dockerfile: ./src/Services/StorageService/Dockerfile
        environment:   
            - DOTNET_ENVIRONMENT=Development        
        depends_on:            
            - rabbitmq

volumes:  
  rabbitmq_data:
    driver: local